### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by haniag** [Wind4/vlmcsd#1]
Here's the command's output:

root@743:~/KMS/scripts# ./install.sh
--2016-09-01 07:42:44--  https://wind4.github.io/vlmcsd/scripts/install-debian.sh
Resolving wind4.github.io (wind4.github.io)... 151.101.56.133
Connecting to wind4.github.io (wind4.github.io)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1163 (1.1K) [application/x-sh]
Saving to: ‘vlmcsd-debian.sh’

100%[==========================================================>] 1,163       --.-K/s   in 0s      

2016-09-01 07:42:44 (158 MB/s) - ‘vlmcsd-debian.sh’ saved [1163/1163]

Downloading vlmcsd ...
Downloading startup script ...
Configuring deamon ...
update-rc.d: warning: /etc/init.d/vlmcsd missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
 Adding system startup for /etc/init.d/vlmcsd ...
   /etc/rc0.d/K20vlmcsd -> ../init.d/vlmcsd
   /etc/rc1.d/K20vlmcsd -> ../init.d/vlmcsd
   /etc/rc6.d/K20vlmcsd -> ../init.d/vlmcsd
   /etc/rc2.d/S20vlmcsd -> ../init.d/vlmcsd
   /etc/rc3.d/S20vlmcsd -> ../init.d/vlmcsd
   /etc/rc4.d/S20vlmcsd -> ../init.d/vlmcsd
   /etc/rc5.d/S20vlmcsd -> ../init.d/vlmcsd
/etc/init.d/vlmcsd: 13: /etc/init.d/vlmcsd: source: not found
Starting service...
Service started.
Installed successfully.

However, I can't activate Windows since I received error about not being able to reach the activation server. Based on above output, am I missing something?

Thanks.

**Comment by Wind4** [comment]
Thanks, my mistake. now is fixed.

**Comment by Wind4** [comment]
If show `VLMCSD service has been installed.` please remove the downloaded file.
```
# rm -f /usr/bin/vlmcsd  
# rm -f /etc/init.d/vlmcsd
```
