### ISSUE TITLE
How is the floppy image built?

### ISSUE THREAD

**Issue by b-** [Wind4/vlmcsd#12]
I’m presuming it can be automated. Can you please provide build scripts for the floppy image?

Thanks!

**Comment by b-** [comment]
I'm definitely more than willing to try, but I should definitely mention that I've never built anything like this before.

Welp, time to download the Linux From Scratch manual!

**Comment by rouben** [comment]
Check my earlier comment: it may be a lot easier/simpler than LFS! :)

**Comment by b-** [comment]
Oh, cool, I didn't see that!

Either way, while I imagine fitting it on a floppy might be difficult for someone inexperienced like myself (and especially if the "magic" really is just the included, custom kernel and ulibc configs), I don't see why I wouldn't be able to build a working image.
