### ISSUE TITLE
vlmcsd on windows without tap adapter

### ISSUE THREAD

**Issue by ale82x** [Wind4/vlmcsd#16]
Hello,
thank you for this software.

Can i install on windows without a tap adapter?
i know kms not working on 127.0.0.1 so i execute this steps 

cmd as admin
netsh int ip add addr 1 192.168.123.2/32 st=persistent sk=tr

then 
slmgr /skms 192.168.123.2
slmgr /ato

but not work...

i wrong in something?

Thank you

**Comment by rouben** [comment]
As far as I am aware, you need the TAP adapter, otherwise the KMS clients built into Office and Windows will not recognize the KMS server. Simply adding an additional IP address to an existing physical network adapter will not trick the system, in my experience..

**Comment by ale82x** [comment]
ok, my problem is when i am offline (without wireless network or ethernet connection) windows 10 show tray icon with an alert ... seems i have problem with internet instead i don't have any connection...

can i "hide" a tap adapter?

thank you
