### ISSUE TITLE
Feature request: Rejecting all activation requests

### ISSUE THREAD

**Issue by lifehome** [Wind4/vlmcsd#17]
I suggest adding a feature to the `-K` switch(e.g. `-K99`), to reject all activation requests, regardless the validity of the requests.

Hoping that this feature could help sysadmins, to identify KMS clients that were missed out from new deployments, while the original KMS server cannot be taken offline yet due to various reasons.

**Comment by rouben** [comment]
Interesting feature.... I'm curious if this can be achieved by using a "dummy" KMS data file?

**Comment by lifehome** [comment]
@rouben I wonder how? The document wrote so little about data file, however, the goal is to fail all activation requests, and I assume the data file consists crucial data to sign off the request? If so, then a false dummy KMS data file would be helpful.

**Comment by rouben** [comment]
Indeed... I’ll need to find some time to figure out the data file format. In the meantime, if anyone else would care to tackle this, please let me know.

**Comment by rouben** [comment]
Your question has been answered, somewhat, [here](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-74#post-1476353), by the original author of the software. It's not the best solution, since it requires a Windows program to generate the binary file, however, it should address your needs, and presumably, it only needs to be done once.

> Yes, download [License Manager 5.0](https://forums.mydigitallife.net/threads/miscellaneous-kms-related-developments.52594/page-32#post-1473186), create a KmsDataBase.xml that only contains definitions for Office 2016.
> 
> ```
> <?xml version="1.0" encoding="Windows-1252"?>
> 
> <KmsData xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="1.7" Author="Hotbird64" xsi:noNamespaceSchemaLocation="KmsDataBase.xsd">
> 
>     <WinBuilds>
>         <WinBuild BuildNumber="1057" DisplayName="Windows NT 3.51" PlatformId="55041" />
>         <WinBuild BuildNumber="1381" DisplayName="Windows NT 4.0" PlatformId="55041" />
>         <WinBuild BuildNumber="2195" DisplayName="Windows 2000" PlatformId="55041" />
>         <WinBuild BuildNumber="2600" DisplayName="Windows XP 32-bit" PlatformId="55041" />
>         <WinBuild BuildNumber="3790" DisplayName="Windows Server 2003 / XP 64-bit" PlatformId="55041" MayBeServer="true" />
>         <WinBuild BuildNumber="6000" DisplayName="Windows Vista / Server 2008 without SP" PlatformId="55041" MayBeServer="true" />
>         <WinBuild BuildNumber="6001" DisplayName="Windows Vista / Server 2008 SP1" PlatformId="55041" MayBeServer="true" />
>         <WinBuild BuildNumber="6002" DisplayName="Windows Vista / Server 2008 SP2" PlatformId="55041" MayBeServer="true" UseForEpid="true" />
>         <WinBuild BuildNumber="7600" DisplayName="Windows 7 / Server 2008 R2 without SP" PlatformId="55041" MayBeServer="true" />
>         <WinBuild BuildNumber="7601" DisplayName="Windows 7 / Server 2008 R2 SP1" PlatformId="55041" MayBeServer="true" UseForEpid="true" />
>         <WinBuild BuildNumber="9200" DisplayName="Windows 8 / Server 2012" PlatformId="5426" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
>         <WinBuild BuildNumber="9600" DisplayName="Windows 8.1 / Server 2012 R2" PlatformId="6401" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
>         <WinBuild BuildNumber="10240" DisplayName="Windows 10 1507" PlatformId="3612" UsesNDR64="true" />
>         <WinBuild BuildNumber="14393" DisplayName="Windows 10 1607 / Server 2016" PlatformId="3612" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
>         <WinBuild BuildNumber="15063" DisplayName="Windows 10 1703" PlatformId="3612" UsesNDR64="true" />
>         <WinBuild BuildNumber="16299" DisplayName="Windows 10 1709" PlatformId="3612" UsesNDR64="true" />
>         <WinBuild BuildNumber="17134" DisplayName="Windows 10 1803" PlatformId="3612" UsesNDR64="true" />
>         <WinBuild BuildNumber="17763" DisplayName="Windows 10 1809 / Server 2019" PlatformId="3612" MayBeServer="true" UseForEpid="true" UsesNDR64="true" />
>     </WinBuilds>
> 
>     <CsvlkItems>
>         <CsvlkItem DisplayName="Office 2016" VlmcsdIndex="0" GroupId="206" MinKeyId="437000000" MaxKeyId="458999999" IniFileName="Office2016" EPid="06401-00206-448-568999-03-1033-9600.0000-3002018" Id="98ebfe73-2084-4c97-932c-c0cd1643bea7">
>             <Activate KmsItem="85b5f61b-320b-4be3-814a-b76b2bfafc82" />
>         </CsvlkItem>
> 
>     </CsvlkItems>
> 
>     <AppItems>
> 
>         <AppItem DisplayName="Office2013+" VlmcsdIndex="0" Id="0ff1ce15-a989-479d-af46-f275c6370663" MinActiveClients="10">
> 
>             <KmsItem DisplayName="Office 2016" Id="85b5f61b-320b-4be3-814a-b76b2bfafc82" IsPreview="false" CanMapToDefaultCsvlk="false" DefaultKmsProtocol="6.0" NCountPolicy="5">
>                 <SkuItem DisplayName="Office Access 2016" Id="67c0fc0c-deba-401b-bf8b-9c8ad8395804" Gvlk="GNH9Y-D2J4T-FJHGG-QRVH7-QPFDW" />
>                 <SkuItem DisplayName="Office Excel 2016" Id="c3e65d36-141f-4d2f-a303-a842ee756a29" Gvlk="9C2PK-NWTVB-JMPW8-BFT28-7FTBF" />
>                 <SkuItem DisplayName="Office Mondo 2016" Id="9caabccb-61b1-4b4b-8bec-d10a3c3ac2ce" Gvlk="HFTND-W9MK4-8B7MJ-B6C4G-XQBR2" />
>                 <SkuItem DisplayName="Office Mondo R 2016" Id="e914ea6e-a5fa-4439-a394-a9bb3293ca09" Gvlk="DMTCJ-KNRKX-26982-JYCKT-P7KB6" />
>                 <SkuItem DisplayName="Office OneNote 2016" Id="d8cace59-33d2-4ac7-9b1b-9b72339c51c8" Gvlk="DR92N-9HTF2-97XKM-XW2WJ-XW3J6" />
>                 <SkuItem DisplayName="Office Outlook 2016" Id="ec9d9265-9d1e-4ed0-838a-cdc20f2551a1" Gvlk="R69KK-NTPKF-7M3Q4-QYBHW-6MT9B" />
>                 <SkuItem DisplayName="Office Powerpoint 2016" Id="d70b1bba-b893-4544-96e2-b7a318091c33" Gvlk="J7MQP-HNJ4Y-WJ7YM-PFYGF-BY6C6" />
>                 <SkuItem DisplayName="Office Professional Plus 2016" Id="d450596f-894d-49e0-966a-fd39ed4c4c64" Gvlk="XQNVK-8JYDB-WJ9W3-YJ8YR-WFG99" />
>                 <SkuItem DisplayName="Office Project Pro 2016" Id="4f414197-0fc2-4c01-b68a-86cbb9ac254c" Gvlk="YG9NW-3K39V-2T3HJ-93F3Q-G83KT" />
>                 <SkuItem DisplayName="Office Project Pro 2016 C2R" Id="829b8110-0e6f-4349-bca4-42803577788d" Gvlk="WGT24-HCNMF-FQ7XH-6M8K7-DRTW9" />
>                 <SkuItem DisplayName="Office Project Standard 2016" Id="da7ddabc-3fbe-4447-9e01-6ab7440b4cd4" Gvlk="GNFHQ-F6YQM-KQDGJ-327XX-KQBVC" />
>                 <SkuItem DisplayName="Office Project Standard 2016 C2R" Id="cbbaca45-556a-4416-ad03-bda598eaa7c8" Gvlk="D8NRQ-JTYM3-7J2DX-646CT-6836M" />
>                 <SkuItem DisplayName="Office Publisher 2016" Id="041a06cb-c5b8-4772-809f-416d03d16654" Gvlk="F47MM-N3XJP-TQXJ9-BP99D-8K837" />
>                 <SkuItem DisplayName="Office Skype for Business 2016" Id="83e04ee1-fa8d-436d-8994-d31a862cab77" Gvlk="869NQ-FJ69K-466HW-QYCP2-DDBV6" />
>                 <SkuItem DisplayName="Office Standard 2016" Id="dedfa23d-6ed1-45a6-85dc-63cae0546de6" Gvlk="JNRGM-WHDWX-FJJG3-K47QV-DRTFM" />
>                 <SkuItem DisplayName="Office Visio Pro 2016" Id="6bf301c1-b94a-43e9-ba31-d494598c47fb" Gvlk="PD3PC-RHNGV-FXJ29-8JK7D-RJRJK" />
>                 <SkuItem DisplayName="Office Visio Pro 2016 C2R" Id="b234abe3-0857-4f9c-b05a-4dc314f85557" Gvlk="69WXN-MBYV6-22PQG-3WGHK-RM6XC" />
>                 <SkuItem DisplayName="Office Visio Standard 2016" Id="aa2a7821-1827-4c2c-8f1d-4513a34dda97" Gvlk="7WHWN-4T7MP-G96JF-G33KR-W8GF4" />
>                 <SkuItem DisplayName="Office Visio Standard 2016 C2R" Id="361fe620-64f4-41b5-ba77-84f8e079b1f7" Gvlk="NY48V-PPYYH-3F4PX-XJRKJ-W4423" />
>                 <SkuItem DisplayName="Office Word 2016" Id="bb11badf-d8aa-470e-9311-20eaf80fe5cc" Gvlk="WXY84-JN2Q9-RBCCQ-3Q3J3-3PFJ6" />
>                 <SkuItem DisplayName="Office Professional Plus 2019 C2R Preview" Id="0bc88885-718c-491d-921f-6f214349e79c" Gvlk="VQ9DP-NVHPH-T9HJC-J9PDT-KTQRG" />
>                 <SkuItem DisplayName="Office Project Pro 2019 C2R Preview" Id="fc7c4d0c-2e85-4bb9-afd4-01ed1476b5e9" Gvlk="XM2V9-DN9HH-QB449-XDGKC-W2RMW" />
>                 <SkuItem DisplayName="Office Visio Pro 2019 C2R Preview" Id="500f6619-ef93-4b75-bcb4-82819998a3ca" Gvlk="N2CG9-YD3YK-936X4-3WR82-Q3X4H" />
>             </KmsItem>
> 
>         </AppItem>
> 
>     </AppItems>
> 
> </KmsData>
> ```
> 
> Load this data into License Manager "File - Load Custom KMS Database" and export it to vlmcsd.kmd "Tools - Export KMS and SKU IDs".
> 
> Upgrade to vlmcsd 1112(important!). In the INI file add KmsData=/path/to/your/vlmcsd.kmd. Make sure that WhitelistingLevel is 3.
> 
>

**Comment by lifehome** [comment]
Just to take note that this file can eliminate all activation request, returning "No such product" error on client side, and resulting an activation failure.

[OfficeMondoR2016_singleEntryOnly.zip](https://github.com/Wind4/vlmcsd/files/2690964/OfficeMondoR2016_singleEntryOnly.zip)
SHA256: `D7B7068918922B06C19620153C099F158BBA0D72452F71BE5249BBDB1998C9A6`

**Comment by rouben** [comment]
@lifehome have you tested the file?

**Comment by lifehome** [comment]
Yes, tho I have only tested it on Windows with localhost parameters only.
