### ISSUE TITLE
hide tap or connection with it

### ISSUE THREAD

**Issue by ale82x** [Wind4/vlmcsd#19]
Hello,
i write on ticket 
https://github.com/Wind4/vlmcsd/issues/16
but it's closed.

can i hide tap adapter ?
because my problem is when i am offline (without wireless network or ethernet connection) windows 10 show tray icon with an alert ... seems i have problem with internet instead i don't have any connection...

so there is a way to hide adapter or connection with it? 

thank you againg

**Comment by rouben** [comment]
Sounds like your TAP adapter may be higher priority in Windows than your actual Internet connection... does [this](https://stackoverflow.com/questions/7785874/setting-network-adapter-metric-priority-in-windows-7#11617518) help?

**Comment by ale82x** [comment]
ok, thank you for idea.

in windows 10 i don't find priority in control panel ... advanced....

anyway i like idea to schedule it every month...

if you this can help me?

- create a kms.bat c:\
- kms.bat contains
`
net start "Key Management Service"
slmgr /ato
sleep 60
net stop "Key Management Service"
`

and schedule it every 1 month  in windows with elevated privileges?

Thank you

**Comment by rouben** [comment]
You also may wish to enable/disable the TAP adapter like so:
`netsh interface set interface "Local Area Connection" DISABLED`
Change "Local Area Connection" to the name of your TAP adapter. Replacing "DISABLED" with "ENABLED" will enable the adapter. You can also use the timeout command to sleep (don't think Windows has sleep?). For example:
`timeout /t 10`

**Comment by ale82x** [comment]
ok thank you...

yes windows don't have sleep but timeout...

i create a batch and schedule it every 3 week

net start  "Key Management Server" >nul
cscript //B "%windir%\system32\slmgr.vbs" /ato
net stop  "Key Management Server" >nul

seems work

thank you
