### ISSUE TITLE
Does it support office2019？

### ISSUE THREAD

**Issue by purezhang** [Wind4/vlmcsd#21]
Does it support office2019？

**Comment by wfsg00098** [comment]
currently not.

**Comment by azgh** [comment]
I have tried to active office 2019, then failed, hope project to update and support to active office 2019.

**Comment by dimqua** [comment]
Version 1112 has been released.

https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/

**Comment by rouben** [comment]
Thanks for the heads up @dimqua, according to the author he will provide full release with binaries in 2-3 days. At this point I’ll update the repo (source code) and upload the latest binaries as a release.

**Comment by mikolatero** [comment]
Binaries released: https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-73#post-1474857

**Comment by wangyq** [comment]
Version 1111 supports office 2019, in my  vmware workstation vitual machine.

**Comment by rouben** [comment]
Thanks for your patience! [Latest release (svn1112)](https://github.com/Wind4/vlmcsd/releases/latest) now has support for Office 2019.
