### ISSUE TITLE
Linux Release for Build 1112

### ISSUE THREAD

**Issue by danfratamico** [Wind4/vlmcsd#27]
When can we expect version 1112 to be release for Linux? I was able to download the current 1112 release for Windows, but I did not find the proper makefile for Linux.

**Comment by rouben** [comment]
Can you elaborate?

The [binaries.tar.gz](https://github.com/Wind4/vlmcsd/releases/download/svn1112/binaries.tar.gz) file contains a variety of Linux (and other OS, including Windows) binaries.

If you're trying to build from source, running "make" should work. Perhaps you're missing a build dependency? In either case, if you want help with the compilation process, please post the output of the make command.
