### ISSUE TITLE
How to run it on Raspberry Pi ?

### ISSUE THREAD

**Issue by Rainy99** [Wind4/vlmcsd#28]
I try to run the arm version on my Raspberry Pi ,but can't execute.

**Comment by arbv** [comment]
Which executable file from the binary distribution are you trying to execute? Does it have executable permissions?

**Comment by Rainy99** [comment]
> Which executable file from the binary distribution are you trying to execute? Does it have executable permissions?

I execute this file: 
_binaries/Linux/arm/big-endian/static/vlmcsd-armeb-nslu2-uclibc-static_
then Output:
Unable to execute binary file: executable file format error
Did I execute the wrong file?
My Raspberry Pi information:
> Model:Raspberry Pi 3B
   OS:Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Comment by rouben** [comment]
I believe armv7l and Easpbian is little-endian by default. Look for 32-bit little-endian ARM binaries, and check permissions as @arbv mentioned above.

**Comment by Rainy99** [comment]
> I believe armv7l and Raspbian is little-endian by default. Look for 32-bit little-endian ARM binaries, and check permissions as @arbv mentioned above.

Little-endian can run successfully,Thanks.
