### ISSUE TITLE
Can't build vlmsc with GCC 9.2

### ISSUE THREAD

**Issue by dukess** [Wind4/vlmcsd#30]
Hello!
Linker can't find libresolv because TARGETPLATFORM in makefile is empty.
Locale and language is ru_RU.UTF-8.
When I set en_US.UTF8 to LC_ALL instead LANG, all work perfect.
No problem with GCC 8.2, 7.3.

bash-5.0# LANG=en_US.UTF8 cc -v 2>&1
Используются внутренние спецификации.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Целевая архитектура: x86_64-pc-linux-gnu
Параметры конфигурации: ../gcc-9.2.0/configure --prefix=/usr --disable-multilib --disable-bootstrap --with-system-zlib --disable-libmpx
Модель многопоточности: posix
gcc версия 9.2.0 (GCC)

bash-5.0# LC_ALL=en_US.UTF8 cc -v 2>&1
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-9.2.0/configure --prefix=/usr --disable-multilib --disable-bootstrap --with-system-zlib --disable-libmpx
Thread model: posix
gcc version 9.2.0 (GCC)

**Comment by rouben** [comment]
To clarify: all works when LC_ALL is set to en-US.UTF8?

**Comment by dukess** [comment]
Sorry, i was wrong.
When i have only LANG variable all works perfect on any system and gcc.
When i have LANG variable and LC_ALL=ru_RU.UTF-8 i got error.

Ok:
-bash-5.0# unset LC_ALL
-bash-5.0# export  LANG=ru_RU.UTF-8
-bash-5.0# LANG=en_US.UTF-8 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-9.2.0/configure --prefix=/usr --disable-multilib --disable-bootstrap --with-system-zlib --disable-libmpx
Thread model: posix
gcc version 9.2.0 (GCC)

Fail:
-bash-5.0# export LC_ALL=ru_RU.UTF-8
-bash-5.0# LANG=en_US.UTF-8 gcc -v
Используются внутренние спецификации.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Целевая архитектура: x86_64-pc-linux-gnu
Параметры конфигурации: ../gcc-9.2.0/configure --prefix=/usr --disable-multilib --disable-bootstrap --with-system-zlib --disable-libmpx
Модель многопоточности: posix
gcc версия 9.2.0 (GCC)

Ok:
-bash-5.0# export LC_ALL=ru_RU.UTF-8
-bash-5.0# LC_ALL=en_US.UTF-8 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-9.2.0/configure --prefix=/usr --disable-multilib --disable-bootstrap --with-system-zlib --disable-libmpx
Thread model: posix
gcc version 9.2.0 (GCC)

**Comment by rouben** [comment]
It seems like things go wrong when LANG and LC_ALL variables don't match. I think this is mentioned [here](https://stackoverflow.com/questions/30479607/explain-the-effects-of-export-lang-lc-ctype-lc-all) specifically this comment: 

> It is worth saying that mixing LANG and LC_CTYPE can give unexpected results

**Comment by dukess** [comment]
What I found:
"LC_ALL  Overrides the value of the LANG environment variable and the values of any other LC_* environment variables."
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/globalization/understand_locale_environ_var.html
and 
https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html

**Comment by rouben** [comment]
From your examples, you can see which language is actually active. 1 and 3 both have English as the active language, and for example 2 it's Russian. Since 2 is the only one that failed, we need to determine what it was caused by: mixing of values of **LANG** and **LC_ALL** of the fact that active language is **ru_RU.UTF-8**?

Can you try something like this?

`unset LC_ALL`
`unset LANG`
`LANG=en_US.UTF-8 make`
`LANG=ru_RU.UTF-8 make`

What do you think?

**Comment by dukess** [comment]
Of course it will work.
I made a patch for my case:
diff -Naur vlmcsd-master/GNUmakefile vlmcsd-master-2/GNUmakefile
--- vlmcsd-master/GNUmakefile   2019-08-08 13:17:04.000000000 +0300
+++ vlmcsd-master-2/GNUmakefile 2019-08-28 15:36:40.764032408 +0300
@@ -14,7 +14,7 @@
 BASE_DLL_NAME=$(notdir $(DLL_NAME))
 BASE_A_NAME=$(notdir $(A_NAME))

-TARGETPLATFORM := $(shell LANG=en_US.UTF-8 $(CC) -v 2>&1 | grep '^Target: ' | cut -f 2 -d ' ')
+TARGETPLATFORM := $(shell LC_ALL=C $(CC) -v 2>&1 | grep '^Target: ' | cut -f 2 -d ' ')

 ifneq (,$(findstring darwin,$(TARGETPLATFORM)))
   DARWIN := 1
diff -Naur vlmcsd-master/src/GNUmakefile vlmcsd-master-2/src/GNUmakefile
--- vlmcsd-master/src/GNUmakefile       2019-08-08 13:17:04.000000000 +0300
+++ vlmcsd-master-2/src/GNUmakefile     2019-08-28 15:36:57.192033168 +0300
@@ -70,7 +70,7 @@
 ################################################################################

 CC ?= gcc
-TARGETPLATFORM := $(shell LANG=en_US.UTF-8 $(CC) -v 2>&1 | grep '^Target: ' | cut -f 2 -d ' ')
+TARGETPLATFORM := $(shell LC_ALL=C $(CC) -v 2>&1 | grep '^Target: ' | cut -f 2 -d ' ')

 ifneq (,$(findstring darwin,$(TARGETPLATFORM)))
   DARWIN := 1

**Comment by rouben** [comment]
Given that this is an unofficial mirror of a private repository that's not open to public, I'd suggest making this request to the [upstream source](https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/) (registration required).

Using C as the locale/language is probably a good idea...
