### ISSUE TITLE
Custom vlmcsd

### ISSUE THREAD

**Issue by ngochoaitn** [Wind4/vlmcsd#31]
Thank Wind4, this portable very good.
Now i want to add new key active for a new production, how to do or custom it?
Thank

**Comment by rouben** [comment]
What key do you want to add?

**Comment by ngochoaitn** [comment]
Such as office 2010

**Comment by ngochoaitn** [comment]
I want to add office 2010 key, and can i custom the expiry date of key?

**Comment by ngochoaitn** [comment]
I try windows 10, windows 7 profestional and office 2013 it worked
But i try active windows 7 ultimate and Office 2010 profestional plus but haven't key for them

**Comment by rouben** [comment]
Windows 7 Ultimate is not a business version, so it will not work with KMS (vlmcsd or any other KMS server).

For Office2010 Pro Plus and all other supported versions and their keys, see https://github.com/Wind4/vlmcsd/blob/gh-pages/README.md

**Comment by ngochoaitn** [comment]
> Windows 7 Ultimate is not a business version, so it will not work with KMS (vlmcsd or any other KMS server). KMS (Key Management Server) is a Microsoft technology that allows businesses to activate their Microsoft Windows and Office products. KMS will not work with home versions of Windows and Office.
> 
> For Office2010 Pro Plus and all other supported versions and their keys, see https://github.com/Wind4/vlmcsd/blob/gh-pages/README.md

Thank you very much, i understand. So, could we use only one key for all product?
