### ISSUE TITLE
Compile with cygwin to x86 binaries.

### ISSUE THREAD

**Issue by username1565** [Wind4/vlmcsd#32]
Is it possible to compile it on windows to win32.exe (x86) binary file, using cygwin? How?

**Comment by rouben** [comment]
The same way you’d compile it on any other platform; the makefile has a cygwin condition built in.

Are you running into an issue? Can you post the log/output?

**Comment by username1565** [comment]
I just run `make CC=gcc` and see `vlmcsd.exe` and `vlmcs.exe` in `/bin/`-folder. But this executables cann't be runned and this is not win32 exe.
How to get make win32 exe, for x86 plaform?
I see you using gmake, not make, and I cann't find gmake package for cygwin,
and maybe `make` this is `GNU make` (gmake).
Maybe I can using some additional parameters with `make` to get x86 win32 exe??

**Comment by rouben** [comment]
Sorry, I misunderstood what you meant... you want to make a win32 x86 exe file that doesn’t need cygwin dependencies to run? Unless you can make a static build (see #33) in cygwin, I’m not sure if you can build something using native Microsoft toolchain in cygwin. You’d need VisualStudio (even Express, the free version) for that, AFAIK. I may be wrong, though, this is just a guess...

Based on this post, it seems like this functionality has been removed from cygwin a while ago and that the task isn’t trivial... https://stackoverflow.com/questions/39090539/compile-winapi-with-cygwin

If you figure it out, let me know! :)

**Comment by username1565** [comment]
Hello, @rouben!
As I said earlier, I didn't saw `gmake` package in `cygwin`, but after this, I see, it is just `make`.
So, I already compiled `vlmcs.exe` and `vlmcsd.exe`, using the following commands:
```
Run cygwin
user@COMPUTER ~
$ cd "C:\projects\vlmcsd-master"

user@COMPUTER /cygdrive/c/projects/vlmcsd-master
$ make CC=gcc
```
After this, I see two compiled exe: `vlmcs.exe` and `vlmcsd.exe`.
But, this cann't be runned on x86 windows, because this not win32 applications.
Maybe, need to use some flags, or another compilator,
and I don't know how to compile this to win32 `exe` (for x86 platform).

**Comment by sskras** [comment]
I think both `CFLAGS` and `LDFLAGS` needs to be extended with this switch.
Not to be harsh, really: https://lmgtfy.com/?q=append+CFLAGS+and+LDFLAGS+from+CLI

**Comment by sskras** [comment]
OK, I see this project doesn't use `autoconf`, so my previous hint is irrelevant. 
In this case I would search that way: https://lmgtfy.com/?q=add+CFLAGS+from+cli

Eg. this hit seems clear enough to me:
https://stackoverflow.com/questions/35072192/how-to-make-make-append-additional-standard-flags

> ![image](https://user-images.githubusercontent.com/7887758/70847509-e4f8ca80-1e6d-11ea-895b-9d3f60ce6295.png)

**Comment by username1565** [comment]
@sskras, hm... I see MakeFile, and this running gmake. In GNUmakefile I don't see any flags.
Maybe need to edit something to run this with flags?

**Comment by rouben** [comment]
@username1565 , you don’t need to worry about gmake with cygwin. Gmake refers to GNU make, and Cygwin is 100% GNU. Same goes for the Makefile; if you actually check the Makefile, you will see it’s a dummy file that references GMakefile and tells you to use GNU make (gmake). If you’re on cygwin or Linux you’re using GNU make (gmake), which by default is called make on these OSs.

The real question is how to run gcc and ldd from Cygwin to compile a static exe with no Cygwin dependencies, so you can run it on a Windows machine with no Cygwin installed. I think it’s doable, just need to look it up for you... stay tuned.

**Comment by rouben** [comment]
So far, this looks promising...
https://stackoverflow.com/questions/38786014/how-to-compile-executable-for-windows-with-gcc-with-linux-subsystem
the above are instructions for WSL on Win10, but I think it would work on Cygwin as well, as long as you can install the **mingw64-i686-gcc** (32-bit) or **mingw64-x86_64-gcc** (64-bit) package in cygwin. Then you would use the same method to compile a static binary (issue #33), just need to specify the mingw64 GCC compiler instead of the one that’s in Cygwin by default, and also make sure -static is passed to ldd.

I don’t have access to a Windows machine at the moment to try this, but I think it can be done...

**Comment by username1565** [comment]
Yes, I just see some `x86`, `win32` executables in `pre-compiled binaries` here: https://github.com/Wind4/vlmcsd/releases/tag/svn1112 , in `binaries.tar.gz`
but I want to get this after compilation of the `source code` to be able to modify it.

I'll try to study this issue, when I will have a free time.
Maybe I really need to install some packages, but maybe this can be fixed more easily, just by using some `flags`.

If you have some great ideas, you can realize this in next commits, and I'll be happy to see this.
_Have a nice day._

**Comment by rouben** [comment]
@username1565 OK, so I tried this on my Ubuntu system. In theory this should also work in Cygwin or WSL on Windows 10.
1. You need to install **mingw64-x86_64-gcc** and **mingw-w64-x86-64**. On Ubuntu/WSL these are installed by installing the **binutils-mingw-w64** and the **gcc-mingw-w64** packages. On Cygwin the instructions are [here](https://www3.ntu.edu.sg/home/ehchua/programming/howto/Cygwin_HowTo.html).
2. You clone the git repo and use this command to compile: **`LDFLAGS=-static CC=x86_64-w64-mingw32-gcc make`** for 64-bit EXEs and **`LDFLAGS=-static CC=i686-w64-mingw32-gcc make`** for 32-bit EXEs. If you're running this on Windows 7, 8, 10 or Windows Server 2008 or better, you probably want 64-bit EXEs. On Windows XP you likely want 32-bit EXEs.
3. Look inside the bin directory, don't forget to rename **`vlmcs`** and **`vlmcsd`** to **`vlmcs.exe`** and **`vlmcsd.exe`** respectively. You can also add 32 or 64 depending on what version you built. You can verify that these are indeed EXEs by using the file command in Ubuntu/WSL and Cygwin. The output of the **`file`** command should say something like this (this was after I built both 32 and 64 bit versions and moved them to a separate directory and renamed them accordingly for easy identification):
```
tchakhma@tank:~$ file ~/vlmcsd-win/*
/home/tchakhma/vlmcsd-win/vlmcs32.exe:  PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
/home/tchakhma/vlmcsd-win/vlmcs64.exe:  PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
/home/tchakhma/vlmcsd-win/vlmcsd32.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
/home/tchakhma/vlmcsd-win/vlmcsd64.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
After copying these to my test Windows 7 64-bit box (the 64-bit EXEs) I tried running them and used both **`vlmcs64.exe`** and **`vlmcs32.exe`** successfully to talk to a test KMS server (one official MS server and another running vlmcsd on a Linux machine). Didn't test **`vlmcsd64.exe`** or **`vlmcsd32.exe`** (actual KMS server EXEs), but see no reason why they shouldn't work (famous last words). There's no cygwin installed on the Windows 7 test box, and I didn't get any prompts for missing DLL files for any of the above files. In other words, these appear to be statically linked and appear to work just fine.
