### ISSUE TITLE
How to build a statically-linked binary

### ISSUE THREAD

**Issue by xczh** [Wind4/vlmcsd#33]
I try to run the following command:

```sh
$ git clone https://github.com/Wind4/vlmcsd
$ cd vlmcsd
$ make
```

And I can find the binary in the `bin` directory.

But how to build a statically-linked binary? Thanks for your help.

**Comment by rouben** [comment]
Good question. You need to install **musl-tools** (Debian/Ubuntu) or its equivalent on your distribution, then compile like this:

`make clean
LDFLAGS=-static CC=musl-gcc make`

**Comment by xczh** [comment]
What about `alpine` for Docker?

**Comment by rouben** [comment]
Try installing (apk add) **musl**, **musl-dev** and **musl-utils**.

**Comment by xczh** [comment]
I got it. Thanks! :)
