### ISSUE TITLE
vlmcsd not binding?

### ISSUE THREAD

**Issue by Zibri** [Wind4/vlmcsd#36]
vlmcsdmulti-Windows-x64.exe vlmcsd -v
Warning: [::]:1688: An attempt was made to access a socket in a way forbidden by its access permissions.
Warning: 0.0.0.0:1688: An attempt was made to access a socket in a way forbidden by its access permissions.
Fatal: Could not listen on any socket.

**Comment by rouben** [comment]
Can you please confirm that:
1. No other process or service is listening on port 1688? For example, did you install vlmcsd as a Windows service and forgot that it's running and bound to port 1688 already?
2. You are running this command in a command prompt window with Administrator privileges (Run as Admin)?
3. Some AntiViruses will detect vlmcsd exes as malware and block it in various ways. Please make sure the exe file is whitelisted on your antivirus.

**Comment by Zibri** [comment]
I found the culprit: it was Hyper-V who was locking the ports.
