### ISSUE TITLE
Is there no `make install`? 

### ISSUE THREAD

**Issue by Mogeko** [Wind4/vlmcsd#39]
Can you add a `make install`? 

It is too inconvenient to install this software now

**Comment by rouben** [comment]
Given the large variety of platforms that this thing is buildable on, making a generic installer would be arduous. Not impossible, but probably a lot of work. There are submodules to build Debian/Ubuntu (deb) packages, as well as a Docker image. Would that suit your needs?

Where/what OS/platform are you trying to build and install this on?

**Comment by Mogeko** [comment]
Thank you for your reply

I want to install on MacOS, I try to [do it with Homebrew](https://github.com/Homebrew/homebrew-core/pull/54057)

**Comment by rouben** [comment]
Thanks for updating the Homebrew bottle. I can confirm it's up to date with latest release of vlmcsd.
Would homebrew work for you? There are instructions for setting it up as a service on a Mac as well.
```
% brew info vlmcsd
vlmcsd: stable svn1113 (bottled), HEAD
KMS Emulator in C
https://github.com/Wind4/vlmcsd
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vlmcsd.rb
==> Dependencies
Build: make ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
The default port is 1688

To configure vlmcsd, edit
  /usr/local/etc/vlmcsd/vlmcsd.ini
After changing the configuration, please restart vlmcsd
  launchctl unload /usr/local/Cellar/vlmcsd/svn1113/homebrew.mxcl.vlmcsd.plist
  launchctl load /usr/local/Cellar/vlmcsd/svn1113/homebrew.mxcl.vlmcsd.plist
Or, if you don't want/need launchctl, you can just run:
  brew services restart vlmcsd

To have launchd start vlmcsd now and restart at login:
  brew services start vlmcsd
Or, if you don't want/need a background service you can just run:
  vlmcsd
```

**Comment by Mogeko** [comment]
Yes, this was submitted by me.

It works now. I opened this issue because I think `make install` will make Homebrew Formula more maintainable.

But considering the workload of implementing `make install`, it may be a good decision to maintain the status quo.

**Comment by rouben** [comment]
The other complication is that this project is technically a copy of the original on MyDigitalLife forums, and the original author doesn't want to collaborate on GitHub. So any changes we make here we have no good way of submitting upstream. If we fork from the original, we're stuck backporting the changes to upstream with every new release...

In any case, thanks for raising this, and thanks for updating the Homebrew formula.
