### ISSUE TITLE
How to determine activated application from the logs

### ISSUE THREAD

**Issue by bengalih** [Wind4/vlmcsd#50]
I'm trying to decipher how to determine what product is being activated.  Windows/Office?  What version?

Looking at logs, the best I see are entries like this:

	Line 20977: 2020-11-20 23:45:27: Application ID                  : 0ff1ce15-a989-479d-af46-f275c6370663 (Unknown)
	Line 20999: 2020-11-20 23:45:31: Application ID                  : 55c92734-d682-4d71-983e-d6ec3f16059f (Unknown)

I assume the first is Office, unless that is a highly coincidental GUID which looks a lot like "office."
But, I don't see anywhere in plain-text what the activated product is.

How can one decipher the logs for this?

**Comment by rouben** [comment]
I believe the data you seek is encoded in the vlmcsd.kmd file. As long as you deploy a copy of this file, and reference it in vlmcsd's config or runtime parameters, you should start seeing product names in logs or console messages. For more info on this, see upstream forum, where the author of the software explains it in more detail (registration is required to access the forum).

**Comment by bengalih** [comment]
Thank you.  I found that file available here:

https://github.com/Wind4/vlmcsd/blob/master/etc/vlmcsd.kmd

Placed it alongside the executable and restarted and now logging properly.
