### ISSUE TITLE
Not working on Windows 10 21H1

### ISSUE THREAD

**Issue by BlackCatNeo** [Wind4/vlmcsd#52]
The error was "The data is invalid".

**Comment by rouben** [comment]
Can you post exactly what steps you took and when exactly you got the error? Please include all commands you ran.

**Comment by BlackCatNeo** [comment]
With a fresh installed Windows 10 21H2 VM, I entered the following commands:

1. slmgr /ipk XXXX-XXXX-XXXX (used one of the GVLK keys provided for Windows 10 Pro)
2. slmgr /skms localhost
3. slmgr /ato

At the last command, the vbs script popup showed "data is invalid" error message

**Comment by rouben** [comment]
See issue #8. Starting with Windows 8, Microsoft started blocking KMS requests to KMS servers running on the same machine.

There are a couple of workarounds:
- Run vlmcsd on a different machine/device on your network. For example, your router.
- Install the OpenVPN TAP driver to create a virtual network interface on your Windows 10 PC, give it an address that's unique (e.g. 10.10.10.10), make sure vlmcsd listens on that IP, and try activation against that IP. This is outlined and automated [here](https://github.com/ekistece/vlmcsd-autokms).

**Comment by rouben** [comment]
I'm closing the issue. Feel free to reopen if you still have the issue despite the explanation above.
