### ISSUE TITLE
Support for Windows Server 2022 and Windows 11

### ISSUE THREAD

**Issue by danfratamico** [Wind4/vlmcsd#55]
Are there plans to support Windows Server 2022 and Windows 11? Microsoft published KMS keys for WS2012 bit not W11 yet.

**Comment by rouben** [comment]
Unless MS changes the KMS protocol, vlmcsd should work with new releases just fine. The new releases likely will not be identified in its logs correctly until the author updates the KMS database file, but that shouldn't affect the ability to activate.

**Comment by rouben** [comment]
I'll be closing this issue. If you still have questions, just comment.

**Comment by si458** [comment]
#57 update server 2022 keys for you :)
