### ISSUE TITLE
Error 0x803f7001 on a computer running non-core edition

### ISSUE THREAD

**Issue by lotekjunky** [Wind4/vlmcsd#56]
When I point my new win10 vm to vlmcsd running in a container on my server, I'm getting an odd error.

`C:\Windows\system32>ver
Microsoft Windows [Version 10.0.19043.1052]
`
When I set slmgr/skms to point to my server, i get a positive message saying that it was pointed properly.
When i run slmgr /ato, it sends a pop window that says "error 0x803f7001 on a computer running Microsoft Windows non-core edition, run slui.exe 0x803f7001 to display the error text."

When I run slui.exe 0x803f7001, it doesn't appear to do anything. No error, no output, no feedback... just line feed and back to the prompt.

I downloaded the ISO directly from microsoft using the media creation tool. when i run slmgr /xpr, it says "windows professional edition: windows is in notification mode."

Has something changed? Did I miss a step?  Is there a way to double check which version of windows I installed? I always install pro, but maybe I clicked the wrong one this time... but I don't know how to tell. The error seems like something I would get while trying to activate the wrong version...

**Comment by lotekjunky** [comment]
So usually what happens is that I start to create an issue and then fill in all of the questions I currently have... and then I'm able to ascertain what I don't know and look into those bits. This time, I submitted it a bit early. I believe I was forgetting to add the /ipk VLK to the mix. I have done that now and am getting different errors.

So, everything is the same, except when I run the /ato command now, i get the message "error 0xc004f074, kms could not be contacted... no KMS server present" more words in it, but that's the gist.

Now on the windows activation applet, i see this:
"we can't activate windows because we can't connect to your organization's server..."  The product ID does say windows 10 pro. The volume license I used from MSFT website is there and you can read the last 'octect' of data and it is correct. product ID ends in AA4360 (I don't know if this is useful or not, so only giving the last bit in case it is sensitive info.)

Sorry to confuse things with 2 really close posts, but this was crucial in the report.

**Comment by si458** [comment]
have you tried the steps here? https://github.com/Wind4/vlmcsd/blob/gh-pages/README.md

**Comment by lotekjunky** [comment]
Thank you for the response, but I'm being a huge dumbass today. I forgot to open the port on my firewall for 1688. I ran a wireshark and it was immediately apparent what was happening. Sorry to bug you, but thanks for the info. I'm activated.

**Comment by si458** [comment]
@lotekjunky brilliant, dont forget to close issue then 👍

**Comment by lotekjunky** [comment]
@si458 right on, thank you. If you log in with Brave Browser, I've sent you a BAT tip you can collect... it's not much but it's something.

**Comment by si458** [comment]
@lotekjunky oh thanks, not sure how i get it but im sure ill find out how haha

**Comment by rouben** [comment]
@lotekjunky nice to meet a fellow Brave/BAT user. 😎👍
