### ISSUE TITLE
能否换自己正版的key

### ISSUE THREAD

**Issue by chspan** [Wind4/vlmcsd#60]
请问是否能换自己的正版lisence，可以请问是修改那个文件

**Comment by BurningC4** [comment]
https://forums.mydigitallife.net/threads/miscellaneous-kms-related-developments.52594/page-39#post-1587290
你可以看一下怎么创建kmd文件，license应该也保存在这里

**Comment by BurningC4** [comment]
如果你的正版kms服务器正在运行，并且假定这台服务器的ip地址是 ```192.168.1.2```
运行 ```vlmcs 192.168.1.2 -G vlmcsd.ini```
产生的 **vlmcsd.ini** 文件里包含了你的正版kms服务器的激活信息

**Comment by rouben** [comment]
Are you trying to change the type of license (e.g. Windows Home to Windows Pro)?

vlmcs is a client for vlmcsd and it's used to test KMS servers.
