### ISSUE TITLE
Hi, will you update to support activate office 2021?

### ISSUE THREAD

**Issue by dmcdark** [Wind4/vlmcsd#63]
Office 2021 is released, are you going to update to support activate Office 2021? 
Thanks a lot!

**Comment by rouben** [comment]
If Microsoft released GVLK (volume license keys) for Office 2021, you are welcome to try activating it. If there are no Volume License Keys for Office 2021, it's possible Microsoft is no longer supporting activation with Office 2021 and is switching to "Click to Run" activations for Office (i.e. Office 365/Microsoft 365 subscription only).

**Comment by dmcdark** [comment]
Oh I see, thank you.

**Comment by dmcdark** [comment]
https://docs.microsoft.com/en-us/DeployOffice/vlactivation/gvlks
Hi, is this Microsoft released GVLK (volume license keys) for Office 2021?

**Comment by dmcdark** [comment]
Thank you for your reply.

My procedure is install retail version, change to volume version by script. Then use KMS to activate. There is a strange thing. I use someone eles kms docker. They use your vlmcsd-1113. I can activate Office2021 LTSC. But in log, it says "KMS v6.0 request from DESKTOP-xxx for Office2013+"
