### ISSUE TITLE
snap in linux snap store

### ISSUE THREAD

**Issue by Kodiman** [Wind4/vlmcsd#74]
hi, Wind4, please consider adding this app to linux snap store with a snapcraft.yaml etc.

this sample snapcraft.yaml code is based on that of kategrey
###########################

name: vlmcsd
version: "1113"
summary: Portable open-source KMS Emulator in C
description: |
  vlmcsd is a replacement for Microsoft's KMS
  server It contains vlmcs a KMS test client, 
  mainly for debugging purposes, that also can
  "charge" a genuine KMS server designed to run
  on an always-on or often-on device,e.g. 
  router, NAS Box, ... intended to help people
  who lost activation of their legally-owned 
  licenses, e.g. due to a change of hardware
  (motherboard, CPU, ...)
confinement: strict
base: core18
grade: stable

apps:
  vlmcs:
    command: vlmcs
    plugs: 
      - network

  vlmcsd:
    command: vlmcsd
    daemon: forking
    plugs:
      - network
      - network-bind

parts:
  vlmcsd:
    plugin: make
    source: https://github.com/Wind4/vlmcsd.git
    source-tag: "1113"
    build-packages:
      - g++
      - make
    artifacts:
      - bin/vlmcs
      - bin/vlmcsd

layout:
  /etc/vlmcsd/vlmcsd.ini:
    symlink: $SNAP_DATA/etc/vlmcsd.ini
  /etc/vlmcsd/vlmcsd.kmd:
    symlink: $SNAP_DATA/etc/vlmcsd.kmd

###############################

**Comment by rouben** [comment]
Why not do it yourself? Looks like you're 90% of the way there already. I bet you could probably automate this too with Github actions. :)
