### ISSUE TITLE
Trojan:Win32/Wacatac.A!ml

### ISSUE THREAD

**Issue by java284284** [Wind4/vlmcsd#78]
there is Trojan:Win32/Wacatac.A!ml in [binaries.tar.gz](https://github.com/Wind4/vlmcsd/releases/download/svn1113/binaries.tar.gz)
Why?

**Comment by si458** [comment]
This is because most antivirus software believe the software is a 'hack' tool to bypass stuff so it gets removed

https://www.virustotal.com/gui/file/a084514ca2a016e2cbbb0471ae0d833e1e7487f8c2b8188d5c8efce8cad455ec

Nothing you can do apart from exclude the file/folder from your antivirus

**Comment by java284284** [comment]
OK  thx

**Comment by thirdwheel** [comment]
I find it hilarious that the likes of Sophos call it a "potentially unwanted application".
