### ISSUE TITLE
Active Failure!

### ISSUE THREAD

**Issue by robinoneway** [Wind4/vlmcsd#83]
My Windows Version: Windows 10 Enterprise LTSC. Version Number: 21H2
Is this Tool don't support my system?

**Comment by thirdwheel** [comment]
Can you be more specific as to the nature of your failure? This doesn't tell us anything about what happened.

**Comment by sempervali** [comment]
Having the same issue. I can provide some more context;
able to verify that vlmcsd IS working, it can still activate other versions, like Windows Server.
Its JUST Windows 10 Enterprise LTSC 2021 that won't activate (using the key M7XTQ-FN8P6-TTKYV-9D4CC-J462D as per official microsoft documentation)
Gives the error 0xC004F074, "The Software Licensing Service reported that the computer could not be activated. No key Management Service (KMS) could be contacted. Please see the Application Event Log for additional information."

**Comment by rouben** [comment]
Can you run vlmcs from the Windows computer? What was the result?

Does the vlmcsd show a connection/activation attempt from the Windows LTSC machine?

Did you set the KMS server IP/hostname using -skms switch as per the instructions?

**Comment by sempervali** [comment]
> Can you run vlmcs from the Windows computer? What was the result?

Yep, runs successfully, no error.
 

> Does the vlmcsd show a connection/activation attempt from the Windows LTSC machine?

Only from vlmcs, running 'slmgr /ato' on the Windows 10 LTSC machine does NOT show any further requests in the log.
Double checked; Windows Server 2022 Datacenter is still able to activate via the vlmcsd server, and request is logged.

> Did you set the KMS server IP/hostname using -skms switch as per the instructions?

Yes, on both the Windows Server and Windows LTSC machines, still exhibits above behavior.

**Comment by rouben** [comment]
Strange... is there something more useful in the event viewer? Usually you get more verbose logs through that.

It seems to me that your Windows 10 LTSC machine doesn't manage to contact the KMS server for some reason. Hopefully the Windows event logs will show why it fails to connect. Could be DNS, could be something else...

**Comment by sempervali** [comment]
This is the only event log info I can see:
The client has sent an activation request to the key management service machine.
Info:
0xC0020017, 0x00000000, 127.0.0.2:1688, e2e90912-b20a-49c7-965f-8ea728ef16eb, 2023/10/08 16:56, 0, 5, 0, 32d2fab3-e4a8-42c2-923b-4bf4fd13e6ee, 25
I noted that it seems to be trying to contact 127.0.0.2:1688, despite the fact that I have specifically set an actual server.
Verified that the normal registry key for the server is set correctly, any ideas?

**Comment by sempervali** [comment]
Answered my own question! I found out that there was a rogue registry key still pointing to this rogue 127.0.0.2 server that doesn't exist. Replacing it manually fixed it. 
![image](https://github.com/Wind4/vlmcsd/assets/15801612/5afc87b3-54a7-4948-9240-54b96ebbb243)
Here's what I was looking through and found the rogue key in. If someone has a similar issue, this may be a fix for it? Worth keeping noted somewhere.
(Highlighted key/folder was what had the broken link)

Replacing broken KMS server IP with active VLMCSD instance immediately allowed 'slmgr /ato' to fully activate the machine.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform\55c92734-d682-4d71-983e-d6ec3f16059f
is the full path to the bad key, probably will differ from machine to machine which is having the issue.
For further context, this is what the key contains
![image](https://github.com/Wind4/vlmcsd/assets/15801612/e517a249-f0a6-4840-9f79-a12c465938e7)

**Comment by rouben** [comment]
Ah, I guess you tried experimenting running vlmcsd on the local machine? That won't work, as you probably already know. Setting the KMS host to any kind of loopback IP or hostname will cause a connection timeout. I think MS hard-coded this in KMS clients.

There's a switch in slmgr to reset its config. Might be helpful if this breaks in the future. I don't recall what that is, though...

**Comment by sempervali** [comment]
I have a feeling this specifically is a leftover from the unofficial installation media I used to originally install the OS, and did notice that this is present on all of the machines I've installed LTSC using said media, so my error may have been more niche. Still, glad that it could be tracked down and fixed.
the flag for resetting the hard set KMS server is slmgr /ckms

**Comment by rouben** [comment]
Good find! I'll close this issue as resolved then.
