### ISSUE TITLE
Can I Use It To Make An Auto-Install vlmcsd Script?

### ISSUE THREAD

**Issue by wwwwjfjf** [Wind4/vlmcsd#84]
I thought that using script to use vlmcsd is difficult for someone.
Can I make it?
PS:I'm gonna put it on GitHub.

**Comment by wwwwjfjf** [comment]
https://github.com/wwwwjfjf/KMS_SERVER_AND_ACTIVITOR

**Comment by thirdwheel** [comment]
It's open source, bro. Of course you can.

**Comment by wwwwjfjf** [comment]
oh thanks :)
