### ISSUE TITLE
not activate Windows 11

### ISSUE THREAD

**Issue by a-rusinov** [Wind4/vlmcsd#88]
not activate Windows 11

**Comment by a-rusinov** [comment]
![Screenshot_1](https://github.com/Wind4/vlmcsd/assets/38038125/d8d7adab-3921-468c-90ef-8d6d5226ba9e)
![Screenshot_2](https://github.com/Wind4/vlmcsd/assets/38038125/1fcfe377-e332-4f34-937a-66810a8a79e4)

**Comment by rouben** [comment]
По адресу видно что вроде вы используете OpenVPN TAP драйвер для коммуникации с vlmcsd? Это важно, т.к. Майкрософт блокирует соединения с localhost адресов (т.е. 127.x.x.x), так что vlmcsd должен быть запущен либо с другой машины на сети, либо подключён к TAP сетевому адаптеру если запускаем его на том же компе который пытаемся активировать.

Ещё проверьте лицензионный ключ. Если у вас Windows 11, то нужно установить ключ Windows 10 соответствующий версии Windows (Pro или Enterprise). Список ключей и инструкции по установке [здесь](https://wind4.github.io/vlmcsd/).

Например Windows 11 Pro = **W269N-WFGWX-YVC9B-4J6C9-T83GX**, а Windows 11 Enterprise = **NPPR9-FWDCX-D2C8J-H872K-2YT43**.

**Comment by a-rusinov** [comment]
это не TAP адаптер, контейнер выполняется в среде Docker на хосте с ос Windows 11. Собственно с родительского хоста этого и пытаюсь активировать его же. 
С остальными клиентами все хорошо.

**Comment by rouben** [comment]
Понятно. К сожалению Windows и Office не принимает ответы от KMS с того же сетевого адаптера, даже если IP адреса разные. Это было обсуждено в #16, а решения в #19, хотя в случае #16 vlmcsd запускался на том же самом компьютере который и пытались активировать. Так как docker по умолчанию использует сеть типа bridge, я думаю что это клиент активации рассматривает как тот же самый хост не смотря на разные IP адреса.

Это искусственное ограничение Microsoft: я уверен что если на родительском хосте запустить vlmcs (KMS клиент) то он без проблем получит ответ от vlmcsd.

Я думаю самый надёжный вариант это установить TAP адаптер на родительский хост и подключить контейнер vlmcsd к локальной сети (т.е. так как и было; чтобы активизировать компьютеры на сети) а так же и к TAP адаптеру (чтобы активизировать родительский хост) как дополнительная сеть контейнера. Потом на родительском хосте поменять адрес KMS сервера на IP адрес TAP адаптера.
