### ISSUE TITLE
能不能自己导入激活码？目录位置在哪里？

### ISSUE THREAD

**Issue by CaiGe666** [Wind4/vlmcsd#94]
使用文件记录的激活密钥文件在哪里？还是这是一个中转站引用另外的网站获取激活秘钥

**Comment by rouben** [comment]
This program implements Microsoft's Key Management Service (KMS) protocol. It's not as simple as storing product keys and sending them to computers that request it. If you want to learn more about it, you can start here: https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys
